"""Shared plumbing for the four exporters.

Every exporter is idempotent: same tokens.yaml in, byte-identical file out, so
re-running one is never a diff. `write_if_changed` also keeps `git status`
quiet when nothing moved.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from presenting_lib.tokens import T, load_tokens  # noqa: E402

IDENTITY = REPO / "identity"

BANNER = (
    "Generated by identity/{script} from identity/tokens.yaml. Do not edit by "
    "hand — change the tokens and re-run."
)


def write_if_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() == content:
        print(f"unchanged  {path.relative_to(REPO)}")
        return False
    path.write_text(content)
    print(f"wrote      {path.relative_to(REPO)}")
    return True


def hex_body(colour: str) -> str:
    return str(colour).lstrip("#").upper()


def rgb01(colour: str) -> tuple[float, float, float]:
    h = hex_body(colour)
    return tuple(int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))


def rgb255(colour: str) -> tuple[int, int, int]:
    h = hex_body(colour)
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


__all__ = ["T", "load_tokens", "REPO", "IDENTITY", "BANNER",
           "write_if_changed", "hex_body", "rgb01", "rgb255"]
